
            extrn   blinkm_avail
            extrn  blinkm_goto_c
            extrn  blinkm_fade_c
            extrn  blinkm_fade_h
            extrn  blinkm_play_s
            extrn  blinkm_stop_s
            extrn  blinkm_set_fs
            extrn  blinkm_set_ta
            extrn  blinkm_set_adr
            extrn  blinkm_get_adr
            extrn  blinkm_get_ver
            extrn  blinkm_get_rgb
            
            
            