
            extrn    pcf8591_avail
            extrn    pcf8591_read
            extrn    pcf8591_off
            extrn    pcf8591_init_s0
            extrn    pcf8591_init_s1
            extrn    pcf8591_init_s2
            extrn    pcf8591_init_s3
            extrn    pcf8591_init_d30
            extrn    pcf8591_init_d31
            extrn    pcf8591_init_d32
            extrn    pcf8591_init_md0
            extrn    pcf8591_init_md1
            extrn    pcf8591_init_md2
            extrn    pcf8591_init_d0
            extrn    pcf8591_init_d1
            
