
            extrn   alnum_init
            extrn   alnum_set_blink_rate
            extrn   alnum_set_blink_off
            extrn   alnum_set_brightness
            extrn   alnum_clear
            extrn   alnum_write_char
            extrn   alnum_write_disp
            extrn   alnum_write_segment
            extrn   alnum_blank_disp
            extrn   alnum_write_colon
            extrn   alnum_write_decimal
            extrn   alnum_chars
            extrn   alnum_display_buf
            extrn   alnum_cmd_buf
            extrn   alnum_avail
