;-------------------------------------------------------------------------------
; Routines used by i2c library routines
;-------------------------------------------------------------------------------

            extrn   i2c_init
            extrn   i2c_wrbuf
            extrn   i2c_rdbuf 
            extrn   i2c_rdreg
            extrn   i2c_avail 
            extrn   i2c_scan 
            extrn   i2c_clear
            extrn   i2c_wraddr
            extrn   i2c_rdaddr 
