
            extrn   lcd_avail
            extrn   lcd_init
            extrn   lcd_clear
            extrn   lcd_home
            extrn   lcd_position
            extrn   lcd_create_char
            extrn   lcd_print_char
            extrn   lcd_print_str
            extrn   lcd_print_nstr
            extrn   lcd_blink_on
            extrn   lcd_blink_off
            extrn   lcd_cursor_on
            extrn   lcd_cursor_off
            extrn   lcd_display_on
            extrn   lcd_display_off
            extrn   lcd_default
            extrn   lcd_backlight_on
            extrn   lcd_backlight_off
            extrn   lcd_entry_mode
            extrn   lcd_auto_on
            extrn   lcd_auto_off
            extrn   lcd_left_to_right
            extrn   lcd_right_to_left
            extrn   lcd_scroll_left
            extrn   lcd_scroll_right
            
