
            extrn   led7_init
            extrn   led7_set_blink_rate
            extrn   led7_set_blink_off
            extrn   led7_set_brightness
            extrn   led7_clear
            extrn   led7_write_digit
            extrn   led7_write_disp
            extrn   led7_write_colon
            extrn   led7_write_blank
            extrn   led7_blank_disp
            extrn   led7_tobcd
            extrn   led7_write_dp
            extrn   led7_digits
            extrn   led7_display_buf
            extrn   led7_cmd_buf
            extrn   led7_avail
            
