;-------------------------------------------------------------------------------
; Number of Printable Characters
;-------------------------------------------------------------------------------

#define C_COUNT      96

;-------------------------------------------------------------------------------
; Public Library Routines
;-------------------------------------------------------------------------------

            extrn   mtrx_init
            extrn   mtrx_avail
            extrn   mtrx_blink_rate
            extrn   mtrx_blink_off
            extrn   mtrx_brightness
            extrn   mtrx_clear
            extrn   mtrx_write_disp
            extrn   mtrx_display_buf
            extrn   mtrx_cmd_buf
            extrn   mtrx_draw_pixel
            extrn   mtrx_draw_bitmap
            extrn   mtrx_draw_char
            extrn   mtrx_print_char
            extrn   mtrx_print_hstr
            extrn   mtrx_print_vstr
            extrn   mtrx_draw_rect
            extrn   mtrx_fill_rect
            extrn   mtrx_draw_line
            
