
            extrn   sht31_clear_status
            extrn   sht31_read_status
            extrn   sht31_avail
            extrn   sht31_init
            extrn   sht31_set_heater
            extrn   sht31_get_heater
            extrn   sht31_read_data
            extrn   sht31_data_buf
            extrn   sht31_temperature_c
            extrn   sht31_temperature_f
            extrn   sht31_humidity
            extrn   sht31_dewpoint_c
            extrn   sht31_dewpoint_f
            extrn   sht31_ready
